name: Code Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          ninja-build \
          lcov \
          libspdlog-dev \
          nlohmann-json3-dev \
          libgtest-dev \
          g++-11

    - name: Configure CMake with Coverage
      env:
        CXX: g++-11
      run: |
        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_CUDA=OFF \
          -DBUILD_TESTS=ON \
          -DENABLE_COVERAGE=ON \
          -DCMAKE_CXX_FLAGS="--coverage -fprofile-arcs -ftest-coverage"

    - name: Build
      run: cmake --build build

    - name: Run Tests
      working-directory: build
      run: ctest --output-on-failure --verbose

    - name: Generate Coverage Report
      working-directory: build
      run: |
        lcov --capture --directory . --output-file coverage.info || echo "No coverage data generated yet"
        if [ -f coverage.info ]; then
          lcov --remove coverage.info '/usr/*' '*/tests/*' '*/third_party/*' --output-file coverage.info
          lcov --list coverage.info
        fi

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./build/coverage.info
        flags: unittests
        name: codecov-bolt
        fail_ci_if_error: false
      continue-on-error: true
